analysis_modules:
  core_personality: true
  dark_triad: true
  cultural_adjustments:
    enabled: true
    default_context: "western"
    available_contexts:
      - western
      - eastern
      - middle_eastern
    
output:
  visualizations: 
    format: "interactive_html"
    export_path: "./reports/"
    themes:
      default: "light"
      available: ["light", "dark", "professional"]
  
  data_privacy:
    anonymization: true
    retention_days: 30
    encryption: true
    storage_location: "./data/secure/"
    
  export_formats:
    - json
    - csv
    - pdf
    - html

analysis_parameters:
  confidence_threshold: 0.7
  minimum_text_length: 100
  maximum_text_length: 10000
  
  scoring:
    big_five:
      weight_openness: 1.0
      weight_conscientiousness: 1.0
      weight_extraversion: 1.0
      weight_agreeableness: 1.0
      weight_neuroticism: 1.0
    
    dark_triad:
      enabled: true
      weight_narcissism: 1.2
      weight_machiavellianism: 1.1
      weight_psychopathy: 1.3

logging:
  level: "INFO"
  file: "./logs/cpas.log"
  max_size_mb: 10
  backup_count: 5

ethical_guidelines:
  consent_required: true
  data_usage_disclaimer: true
  professional_use_only: true
  confidentiality_agreement: true 