apiVersion: 1

notifiers:
  - name: email-notifier
    type: email
    uid: email
    is_default: true
    settings:
      addresses: admin@yourdomain.com
      singleEmail: true

  - name: slack-notifier
    type: slack
    uid: slack
    settings:
      url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
      token: your-slack-token
      recipient: '#alerts'
      username: 'CPAS Alert'
      iconEmoji: ':warning:'
      iconUrl: ''
      mentionUsers: ''
      mentionGroups: ''
      mentionChannel: ''
      skipResolve: false

  - name: pagerduty-notifier
    type: pagerduty
    uid: pagerduty
    settings:
      integrationKey: your-pagerduty-key
      severity: critical
      autoResolve: true
      message: '{{ template "default.message" . }}' 