apiVersion: 1

groups:
  - name: CPAS Alerts
    folder: CPAS
    interval: 1m
    rules:
      - uid: high-error-rate
        title: High Error Rate
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100
              intervalMs: 15000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for the last 5 minutes
        labels:
          severity: critical

      - uid: high-latency
        title: High Request Latency
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])
              intervalMs: 15000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: High request latency detected
          description: Average request latency is above 1 second for the last 5 minutes
        labels:
          severity: warning

      - uid: service-down
        title: Service Down
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: up{job="cpas"}
              intervalMs: 15000
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              refId: B
              type: classic_conditions
        noDataState: Alerting
        execErrState: Error
        for: 1m
        annotations:
          summary: Service is down
          description: The CPAS service is not responding
        labels:
          severity: critical 